spring:
  application:
    name: visits-back-office
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 30000
        max-interval: 100000