logging:
  level:
    telran: trace

spring:
  kafka:
    bootstrap-servers: glider.srvs.cloudkafka.com:9094
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="kclgkokd" password="${CLOUDKARAFKA_PASSWORD}";
  cloud:
    stream:
      bindings:
        jumpsConsumer-in-0:
          destination: lwnrvyhm-jumps
          group: lwnrvyhm-notifier

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true