logging:
  level:
    telran: trace

spring:
  kafka:
    bootstrap-servers: glider.srvs.cloudkafka.com:9094
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="lwnrvyhm" password="${CLOUDKARAFKA_PASSWORD}";
  cloud:
    stream:
      bindings:
        jumpsConsumer-in-0:
          destination: lwnrvyhm-jumps
          group: lwnrvyhm-notifier